### ISSUE TITLE
Sugestões de melhorias

### ISSUE THREAD

**Issue by ftonato** [davidalves1/clima-app#2]
E aí @davidalves1 legal o projeto e tenho algumas sugestões de melhorias =)
- [x] Validar a `cidade` digitada pelo usuário.
1. Digitei apenas `tempo` no terminal (sem passar a cidade) e retornou algo, todavia não sei para qual cidade ele fez a busca.
2. Digitei duas cidades separadas por vírgula e também não sei para qual delas ele fez a busca.
- [ ] Adicionar uma busca por várias cidades. _feature interessante_
- [x] Adicionar a Licença no [readme.md](https://github.com/davidalves1/clima-app/blob/master/readme.md)

Posso ajudar a implementar se quiser :+1: 

Abraço

**Comment by davidalves1** [comment]
Opa.. Toda contribuição é muito bem vinda!

**Comment by ftonato** [comment]
O commit _Melhorias na documentação e algumas sugestões da issue #2_ não existe, foi falha minha haha
Todavia o segundo _Melhorias na doc. e sugestões da issue #2_ está correto ;)

**Comment by davidalves1** [comment]
Valeu pela contribuição @ftonato! Já fiz o merge e mais tarde vou subir a atualização para o npm!
